<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Combined Report - {{ $months[$month] }} {{ $year }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .container {
            width: 100%;
            margin: 0 auto;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 18px;
            margin: 0;
        }
        .header p {
            font-size: 12px;
            margin: 5px 0;
        }
        .section {
            margin-bottom: 20px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }
        .table th {
            background-color: #f4f4f4;
            font-weight: bold;
        }
        .table td.right {
            text-align: right;
        }
        .footer {
            text-align: center;
            font-size: 10px;
            color: #777;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Combined OT & Holiday Pay Report</h1>
            <p>Period: {{ $months[$month] }} {{ $year }}</p>
            <p>Generated on: {{ $report_date }}</p>
        </div>

        <!-- Holiday Payout Section -->
        <div class="section">
            <h3>Holiday Pay</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Employee Name</th>
                        <th>Holiday Work Days</th>
                        <th>Total Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($holiday_payout_records as $record)
                        <tr>
                            <td>{{ $record->employee_name }}</td>
                            <td>{{ number_format($record->holiday_work_days, 2) }}</td>
                            <td>{{ number_format($record->holiday_amount, 2) }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3" class="center">No holiday payout records found</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        <!-- Overtime Section -->
        <div class="section">
            <h3>OT Hours</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Employee Name</th>
                        <th>OT Hours</th>
                        <th>Total Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($overtime_records as $record)
                        <tr>
                            <td>{{ $record->employee_name }}</td>
                            <td>{{ number_format($record->ot_hours, 2) }}</td>
                            <td>{{ number_format($record->ot_amount, 2) }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3" class="center">No overtime records found</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        <!-- Consolidated Section -->
        <div class="section">
            <h3>Consolidated</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Employee Name</th>
                        <th>Total Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($consolidated_records as $record)
                        <tr>
                            <td>{{ $record->employee_name }}</td>
                            <td>{{ number_format($record->consolidated_amount, 2) }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="2" class="center">No consolidated records found</td>
                        </tr>
                    @endforelse
                    <tr>
                        <td><strong>Total</strong></td>
                        <td><strong>{{ number_format($total_consolidated, 2) }}</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="footer">
            <p>Generated by Payroll System</p>
        </div>
    </div>
</body>
</html>