<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report_type === 'overtime' ? 'Overtime Report' : 'Holiday Payout Report' }} - {{ $months[$month] }} {{ $year }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .container {
            width: 100%;
            margin: 0 auto;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 18px;
            margin: 0;
        }
        .header p {
            font-size: 12px;
            margin: 5px 0;
        }
        .summary {
            margin-bottom: 20px;
        }
        .summary-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .summary-table th, .summary-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }
        .summary-table th {
            background-color: #f4f4f4;
            font-weight: bold;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        .table th {
            background-color: #f4f4f4;
            font-weight: bold;
        }
        .table td.right {
            text-align: right;
        }
        .table td.center {
            text-align: center;
        }
        .footer {
            text-align: center;
            font-size: 10px;
            color: #777;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{{ $report_type === 'overtime' ? 'Overtime Report' : 'Holiday Payout Report' }}</h1>
            <p>Period: {{ $months[$month] }} {{ $year }}</p>
            <p>Generated on: {{ $report_date }}</p>
        </div>

        <!-- Summary Statistics -->
        <div class="summary">
            <table class="summary-table">
                <tr>
                    <th>{{ $report_type === 'overtime' ? 'Total OT Hours' : 'Total Holiday Work Days' }}</th>
                    <th>Total Amount</th>
                    <th>{{ $report_type === 'overtime' ? 'Average OT Hours' : 'Average Holiday Work Days' }}</th>
                </tr>
                <tr>
                    <td>{{ number_format($total_hours_or_days, 2) }}</td>
                    <td>{{ number_format($total_amount, 2) }}</td>
                    <td>{{ number_format($avg_hours_or_days, 2) }}</td>
                </tr>
            </table>
        </div>

        <!-- Records Table -->
        <table class="table">
            <thead>
                <tr>
                    <th>Employee ID</th>
                    <th>Employee Name</th>
                    <th>Month</th>
                    <th>Year</th>
                    <th class="right">{{ $report_type === 'overtime' ? 'OT Hours' : 'Holiday Work Days' }}</th>
                    <th class="right">{{ $report_type === 'overtime' ? 'Rate/Hour' : 'Rate/Day' }}</th>
                    <th class="right">Total Amount</th>
                </tr>
            </thead>
            <tbody>
                @forelse($records as $record)
                    <tr>
                        <td>{{ $record->employee_code }}</td>
                        <td>{{ $record->employee_name }}</td>
                        <td>{{ $months[$record->payout_month] }}</td>
                        <td>{{ $record->payout_year }}</td>
                        <td class="right">{{ number_format($record->ot_hours, 2) }}</td>
                        <td class="right">{{ number_format($record->ot_rate, 2) }}</td>
                        <td class="right">{{ number_format($record->total_amount, 2) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" class="center">No records found</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <div class="footer">
            <p>Generated by Payroll System</p>
        </div>
    </div>
</body>
</html>